name: Install by ssh
on: push

jobs:
  install-by-ssh:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.WINTYO_SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install
        run: yarn install

      - name: Run
        run: yarn start
