name: Install by PAT
on: push

jobs:
  install-by-pat:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WINTYO_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Setup ssh url
        run: |
          git config --global url."https://x-access-token:${{ secrets.WINTYO_PAT }}@github.com/wintyo-ssh-packages".insteadOf "git@github.com:wintyo-ssh-packages"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run
        run: yarn start
