name: Install by ssh
on: push

jobs:
  install-by-ssh:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: SSH Setting
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e "$SSH_KEY" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.WINTYO_SSH_KEY }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run
        run: yarn start
