name: trial
on: push

jobs:
  trial:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Check WINTYO_PAT
        run: |
          echo ${{ secrets.WINTYO_PAT }}
          echo ${{ secrets.HOGE }}

      - name: Setup ssh url
        run: |
          git config --global url."https://${{ secrets.WINTYO_PAT }}:x-oauth-basic@github.com/wintyo-ssh-packages".insteadOf "git@github.com:wintyo-ssh-packages"
          git config --global url."https://${{ secrets.WINTYO_PAT }}:x-oauth-basic@github.com/wintyo-ssh-packages/private-utils".insteadOf "git@github.com:wintyo-ssh-packages/private-utils"

      - name: Install
        run: yarn install

      - name: Run
        run: yarn start
